CREATE TABLE roles (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(32) NOT NULL,
    CONSTRAINT uk_roles_name UNIQUE (name)
);

CREATE TABLE users (
    id            UUID PRIMARY KEY,
    first_name    VARCHAR(100)             NOT NULL,
    last_name     VARCHAR(100)             NOT NULL,
    email         VARCHAR(255)             NOT NULL,
    password_hash VARCHAR(100)             NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE user_roles (
    user_id UUID   NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES roles (id),
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE accounts (
    id             UUID PRIMARY KEY,
    account_number VARCHAR(20)              NOT NULL,
    account_type   VARCHAR(20)              NOT NULL,
    balance        NUMERIC(19, 2)           NOT NULL,
    status         VARCHAR(20)              NOT NULL,
    owner_id       UUID                     NOT NULL REFERENCES users (id),
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    version        BIGINT                   NOT NULL,
    CONSTRAINT uk_accounts_account_number UNIQUE (account_number),
    CONSTRAINT ck_accounts_balance_non_negative CHECK (balance >= 0),
    CONSTRAINT ck_accounts_type CHECK (account_type IN ('CHECKING', 'SAVINGS')),
    CONSTRAINT ck_accounts_status CHECK (status IN ('ACTIVE', 'FROZEN', 'CLOSED'))
);

CREATE INDEX idx_accounts_owner_id ON accounts (owner_id);

CREATE TABLE transactions (
    id                     UUID PRIMARY KEY,
    transaction_type       VARCHAR(20)              NOT NULL,
    amount                 NUMERIC(19, 2)           NOT NULL,
    source_account_id      UUID REFERENCES accounts (id),
    destination_account_id UUID REFERENCES accounts (id),
    status                 VARCHAR(20)              NOT NULL,
    description            VARCHAR(255),
    failure_reason         VARCHAR(255),
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_transactions_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_transactions_has_account CHECK (source_account_id IS NOT NULL OR destination_account_id IS NOT NULL),
    CONSTRAINT ck_transactions_type CHECK (transaction_type IN ('DEPOSIT', 'WITHDRAWAL', 'TRANSFER')),
    CONSTRAINT ck_transactions_status CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED'))
);

CREATE INDEX idx_transactions_source_account ON transactions (source_account_id, created_at);
CREATE INDEX idx_transactions_destination_account ON transactions (destination_account_id, created_at);

INSERT INTO roles (name) VALUES ('CUSTOMER'), ('ADMIN');
